// <auto-generated />
using System;
using BitCollegeWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitCollegeWeb.Data.Migrations
{
    [DbContext(typeof(DbContextBitCollegeWeb))]
    partial class DbContextBitCollegeWebModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BitCollegeWeb.Entities.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("announcement_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateLimit")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_limit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("title");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("SectionId");

                    b.ToTable("announcement");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CalificationAssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("calification_assignment_id");

                    b.Property<DateTime>("DateLimit")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_limit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("DocumentLink")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("document_link");

                    b.Property<bool>("PendingComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("pending_complete")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<bool>("SentNotSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("sent_notsent")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("shipping_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("title");

                    b.HasKey("AssignmentId");

                    b.HasIndex("CalificationAssignmentId");

                    b.HasIndex("SectionId");

                    b.ToTable("assignment");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.CalificationAssignment", b =>
                {
                    b.Property<int>("CalificationAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("calification_assignment_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("comment");

                    b.Property<bool>("CommentPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("comment_published")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("Note")
                        .HasColumnType("int")
                        .HasColumnName("note");

                    b.HasKey("CalificationAssignmentId");

                    b.ToTable("calification_assignment");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.CalificationExam", b =>
                {
                    b.Property<int>("CalificationExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("calification_exam_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Note")
                        .HasColumnType("int")
                        .HasColumnName("note");

                    b.HasKey("CalificationExamId");

                    b.ToTable("calification_exam");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.CalificationSystem", b =>
                {
                    b.Property<int>("CalificationSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("calification_system_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumberPercentage")
                        .HasColumnType("int")
                        .HasColumnName("number_percentage");

                    b.HasKey("CalificationSystemId");

                    b.ToTable("calification_system");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.CalificationSystemTypeCalification", b =>
                {
                    b.Property<int>("CalificationSystemId")
                        .HasColumnType("int")
                        .HasColumnName("calification_system_id");

                    b.Property<int>("TypeCalificationId")
                        .HasColumnType("int")
                        .HasColumnName("type_calification_id");

                    b.HasKey("CalificationSystemId", "TypeCalificationId");

                    b.HasIndex("TypeCalificationId");

                    b.ToTable("calification_system_type_calification");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("chat_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int")
                        .HasColumnName("classroom_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("content");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("ChatId");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("chat");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("classroom_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_start");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<int>("TeacherForumId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_forum_id");

                    b.Property<int?>("TeacherForumId1")
                        .HasColumnType("int");

                    b.HasKey("ClassroomId");

                    b.HasIndex("SectionId");

                    b.HasIndex("TeacherForumId");

                    b.HasIndex("TeacherForumId1")
                        .IsUnique()
                        .HasFilter("[TeacherForumId1] IS NOT NULL");

                    b.ToTable("classroom");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.ClassroomExternalTool", b =>
                {
                    b.Property<int>("ExternalToolId")
                        .HasColumnType("int")
                        .HasColumnName("external_tool_id");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int")
                        .HasColumnName("classroom_id");

                    b.HasKey("ExternalToolId", "ClassroomId");

                    b.HasIndex("ClassroomId");

                    b.ToTable("classroom_external_tool");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("company_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("CompanyId");

                    b.ToTable("company");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Day", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("day_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("DayId");

                    b.ToTable("day");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Evidence", b =>
                {
                    b.Property<int>("EvidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("evidence_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EvidenceLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("evidence_link");

                    b.Property<int>("TeacherForumId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_forum_id");

                    b.HasKey("EvidenceId");

                    b.HasIndex("TeacherForumId");

                    b.ToTable("evidence");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("exam_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CalificationExamId")
                        .HasColumnType("int")
                        .HasColumnName("calification_exam_id");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_start");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("FinishTime")
                        .HasColumnType("int")
                        .HasColumnName("finish_time");

                    b.Property<bool>("PendingComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("pending_complete")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<bool>("SentNotSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("sent_notsent")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("StartTime")
                        .HasColumnType("int")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("title");

                    b.HasKey("ExamId");

                    b.HasIndex("CalificationExamId");

                    b.HasIndex("SectionId");

                    b.ToTable("exam");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.ExternalTool", b =>
                {
                    b.Property<int>("ExternalToolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("external_tool_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("ExternalToolId");

                    b.ToTable("external_tool");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.GeneralInformation", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("int")
                        .HasColumnName("topic_id");

                    b.Property<int>("ProgrammingStudyId")
                        .HasColumnType("int")
                        .HasColumnName("programming_study_id");

                    b.HasKey("TopicId", "ProgrammingStudyId");

                    b.HasIndex("ProgrammingStudyId");

                    b.ToTable("general_information");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Inscription", b =>
                {
                    b.Property<int>("InscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inscription_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_inscription");

                    b.Property<int>("ProgrammingStudyId")
                        .HasColumnType("int")
                        .HasColumnName("programming_study_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("InscriptionId");

                    b.HasIndex("ProgrammingStudyId");

                    b.HasIndex("StudentId");

                    b.ToTable("inscription");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Institution", b =>
                {
                    b.Property<int>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("institution_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("InstitutionId");

                    b.ToTable("institution");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("title");

                    b.HasKey("NotificationId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("notification");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.ProgrammingStudy", b =>
                {
                    b.Property<int>("ProgrammingStudyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("programming_study_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CalificationSystemId")
                        .HasColumnType("int")
                        .HasColumnName("calification_system_id");

                    b.Property<int?>("CalificationSystemId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<int>("TypeProgrammingClassId")
                        .HasColumnType("int")
                        .HasColumnName("type_programming_class_id");

                    b.Property<int>("TypeStudyId")
                        .HasColumnType("int")
                        .HasColumnName("type_study_id");

                    b.HasKey("ProgrammingStudyId");

                    b.HasIndex("CalificationSystemId");

                    b.HasIndex("CalificationSystemId1")
                        .IsUnique()
                        .HasFilter("[CalificationSystemId1] IS NOT NULL");

                    b.HasIndex("TypeProgrammingClassId");

                    b.HasIndex("TypeStudyId");

                    b.ToTable("programming_study");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("registration_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("RegistrationId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("registration");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("TypeProgrammingClassId")
                        .HasColumnType("int")
                        .HasColumnName("type_programming_class_id");

                    b.Property<int?>("TypeProgrammingClassId1")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TypeProgrammingClassId");

                    b.HasIndex("TypeProgrammingClassId1")
                        .IsUnique()
                        .HasFilter("[TypeProgrammingClassId1] IS NOT NULL");

                    b.ToTable("schedule");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.ScheduleDay", b =>
                {
                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.Property<int>("DayId")
                        .HasColumnType("int")
                        .HasColumnName("day_id");

                    b.Property<int>("FinishTime")
                        .HasColumnType("int")
                        .HasColumnName("finish_time");

                    b.Property<int>("StartTime")
                        .HasColumnType("int")
                        .HasColumnName("start_time");

                    b.HasKey("ScheduleId", "DayId");

                    b.HasIndex("DayId");

                    b.ToTable("schedule_day");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("section_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumberRecordings")
                        .HasColumnType("int")
                        .HasColumnName("number_recordings");

                    b.Property<int>("NumberStudentsEnroll")
                        .HasColumnType("int")
                        .HasColumnName("number_students_enroll");

                    b.Property<int>("ProgrammingStudyId")
                        .HasColumnType("int")
                        .HasColumnName("programming_study_id");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("section_code");

                    b.Property<bool>("Vacancies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("vacancies")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("SectionId");

                    b.HasIndex("ProgrammingStudyId");

                    b.ToTable("section");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.SectionTypeSection", b =>
                {
                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<int>("TypeSectionId")
                        .HasColumnType("int")
                        .HasColumnName("type_section_id");

                    b.HasKey("SectionId", "TypeSectionId");

                    b.HasIndex("TypeSectionId");

                    b.ToTable("section_type_section");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentExperienceId")
                        .HasColumnType("int")
                        .HasColumnName("student_experience_id");

                    b.Property<int?>("StudentExperienceId1")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentExperienceId");

                    b.HasIndex("StudentExperienceId1")
                        .IsUnique()
                        .HasFilter("[StudentExperienceId1] IS NOT NULL");

                    b.ToTable("student");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.StudentExperience", b =>
                {
                    b.Property<int>("StudentExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_experience_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateStartProgramming")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_start_programming");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int")
                        .HasColumnName("institution_id");

                    b.HasKey("StudentExperienceId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("student_experience");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.StudentSection", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.HasKey("StudentId", "SectionId");

                    b.HasIndex("SectionId");

                    b.ToTable("student_section");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("teacher_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherExperienceId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_experience_id");

                    b.Property<int?>("TeacherExperienceId1")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId");

                    b.HasIndex("TeacherExperienceId");

                    b.HasIndex("TeacherExperienceId1")
                        .IsUnique()
                        .HasFilter("[TeacherExperienceId1] IS NOT NULL");

                    b.ToTable("teacher");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TeacherExperience", b =>
                {
                    b.Property<int>("TeacherExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("teacher_experience_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("DateStartProgramming")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_start_programming");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("position");

                    b.HasKey("TeacherExperienceId");

                    b.HasIndex("CompanyId");

                    b.ToTable("teacher_experience");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TeacherForum", b =>
                {
                    b.Property<int>("TeacherForumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("teacher_forum_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("problem_description");

                    b.HasKey("TeacherForumId");

                    b.ToTable("teacher_forum");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TeacherSection", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.HasKey("TeacherId", "SectionId");

                    b.HasIndex("SectionId");

                    b.ToTable("teacher_section");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("topic_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("TopicId");

                    b.ToTable("topic");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TypeCalification", b =>
                {
                    b.Property<int>("TypeCalificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("type_calification_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("TypeCalificationId");

                    b.ToTable("type_calification");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TypeProgrammingClass", b =>
                {
                    b.Property<int>("TypeProgrammingClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("type_programming_class_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("TypeProgrammingClassId");

                    b.ToTable("type_programming_class");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TypeSection", b =>
                {
                    b.Property<int>("TypeSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("type_section_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("TypeSectionId");

                    b.ToTable("type_section");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TypeStudy", b =>
                {
                    b.Property<int>("TypeStudyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("type_study_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("TypeStudyId");

                    b.ToTable("type_study");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.URL", b =>
                {
                    b.Property<int>("UrlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("url_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExternalToolId")
                        .HasColumnType("int")
                        .HasColumnName("external_tool_id");

                    b.Property<int>("TopicId")
                        .HasColumnType("int")
                        .HasColumnName("topic_id");

                    b.Property<string>("UrlLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("url_link");

                    b.HasKey("UrlId");

                    b.HasIndex("ExternalToolId");

                    b.HasIndex("TopicId");

                    b.ToTable("url");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Announcement", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Section", "Section")
                        .WithMany("Announcements")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_section_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Assignment", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.CalificationAssignment", "CalificationAssignment")
                        .WithMany("Assignments")
                        .HasForeignKey("CalificationAssignmentId")
                        .HasConstraintName("FK_calification_assignment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.Section", "Section")
                        .WithMany("Assignments")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_section_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalificationAssignment");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.CalificationSystemTypeCalification", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.CalificationSystem", "CalificationSystem")
                        .WithMany("CalificationSystemTypeCalifications")
                        .HasForeignKey("CalificationSystemId")
                        .HasConstraintName("FK_calification_system_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.TypeCalification", "TypeCalification")
                        .WithMany("CalificationSystemTypeCalifications")
                        .HasForeignKey("TypeCalificationId")
                        .HasConstraintName("FK_type_calification_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalificationSystem");

                    b.Navigation("TypeCalification");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Chat", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Classroom", "Classroom")
                        .WithMany("Chats")
                        .HasForeignKey("ClassroomId")
                        .HasConstraintName("FK_classroom_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.Teacher", "Teacher")
                        .WithMany("Chats")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Classroom", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Section", "Section")
                        .WithMany("Classrooms")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_section_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.TeacherForum", "TeacherForum")
                        .WithMany()
                        .HasForeignKey("TeacherForumId")
                        .HasConstraintName("FK_teacher_forum_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.TeacherForum", null)
                        .WithOne("Classroom")
                        .HasForeignKey("BitCollegeWeb.Entities.Classroom", "TeacherForumId1");

                    b.Navigation("Section");

                    b.Navigation("TeacherForum");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.ClassroomExternalTool", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Classroom", "Classroom")
                        .WithMany("ClassroomExternalTools")
                        .HasForeignKey("ClassroomId")
                        .HasConstraintName("FK_classroom_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.ExternalTool", "ExternalTool")
                        .WithMany("ClassroomExternalTools")
                        .HasForeignKey("ExternalToolId")
                        .HasConstraintName("FK_external_tool_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("ExternalTool");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Evidence", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.TeacherForum", "TeacherForum")
                        .WithMany("Evidences")
                        .HasForeignKey("TeacherForumId")
                        .HasConstraintName("FK_teacher_forum_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherForum");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Exam", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.CalificationExam", "CalificationExam")
                        .WithMany("Exams")
                        .HasForeignKey("CalificationExamId")
                        .HasConstraintName("FK_calification_exam_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.Section", "Section")
                        .WithMany("Exams")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_section_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalificationExam");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.GeneralInformation", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.ProgrammingStudy", "ProgrammingStudy")
                        .WithMany("GeneralInformations")
                        .HasForeignKey("ProgrammingStudyId")
                        .HasConstraintName("FK_programming_study_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.Topic", "Topic")
                        .WithMany("GeneralInformations")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("FK_topic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammingStudy");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Inscription", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.ProgrammingStudy", "ProgrammingStudy")
                        .WithMany("Inscriptions")
                        .HasForeignKey("ProgrammingStudyId")
                        .HasConstraintName("FK_programming_study_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.Student", "Student")
                        .WithMany("Inscriptions")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammingStudy");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Notification", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Student", "Student")
                        .WithMany("Notifications")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.Teacher", "Teacher")
                        .WithMany("Notifications")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.ProgrammingStudy", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.CalificationSystem", "CalificationSystem")
                        .WithMany()
                        .HasForeignKey("CalificationSystemId")
                        .HasConstraintName("FK_calification_system_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.CalificationSystem", null)
                        .WithOne("ProgrammingStudy")
                        .HasForeignKey("BitCollegeWeb.Entities.ProgrammingStudy", "CalificationSystemId1");

                    b.HasOne("BitCollegeWeb.Entities.TypeProgrammingClass", "TypeProgrammingClass")
                        .WithMany("ProgrammingStudies")
                        .HasForeignKey("TypeProgrammingClassId")
                        .HasConstraintName("FK_type_programming_class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.TypeStudy", "TypeStudy")
                        .WithMany("ProgrammingStudies")
                        .HasForeignKey("TypeStudyId")
                        .HasConstraintName("FK_type_study_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalificationSystem");

                    b.Navigation("TypeProgrammingClass");

                    b.Navigation("TypeStudy");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Registration", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Student", "Student")
                        .WithMany("Registrations")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.Teacher", "Teacher")
                        .WithMany("Registrations")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Schedule", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Student", "Student")
                        .WithMany("Schedules")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.TypeProgrammingClass", "TypeProgrammingClass")
                        .WithMany()
                        .HasForeignKey("TypeProgrammingClassId")
                        .HasConstraintName("FK_type_programming_class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.TypeProgrammingClass", null)
                        .WithOne("Schedule")
                        .HasForeignKey("BitCollegeWeb.Entities.Schedule", "TypeProgrammingClassId1");

                    b.Navigation("Student");

                    b.Navigation("TypeProgrammingClass");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.ScheduleDay", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Day", "Day")
                        .WithMany("ScheduleDays")
                        .HasForeignKey("DayId")
                        .HasConstraintName("FK_day_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.Schedule", "Schedule")
                        .WithMany("ScheduleDays")
                        .HasForeignKey("ScheduleId")
                        .HasConstraintName("FK_schedule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Section", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.ProgrammingStudy", "ProgrammingStudy")
                        .WithMany()
                        .HasForeignKey("ProgrammingStudyId")
                        .HasConstraintName("FK_programming_study_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammingStudy");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.SectionTypeSection", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Section", "Section")
                        .WithMany("SectionTypeSections")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_section_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.TypeSection", "TypeSection")
                        .WithMany("SectionTypeSections")
                        .HasForeignKey("TypeSectionId")
                        .HasConstraintName("FK_type_section_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("TypeSection");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Student", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.StudentExperience", "StudentExperience")
                        .WithMany()
                        .HasForeignKey("StudentExperienceId")
                        .HasConstraintName("FK_student_experience_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.StudentExperience", null)
                        .WithOne("Student")
                        .HasForeignKey("BitCollegeWeb.Entities.Student", "StudentExperienceId1");

                    b.Navigation("StudentExperience");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.StudentExperience", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Institution", "Institution")
                        .WithMany("StudentExperiences")
                        .HasForeignKey("InstitutionId")
                        .HasConstraintName("FK_institution_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.StudentSection", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Section", "Section")
                        .WithMany("StudentSections")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_section_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.Student", "Student")
                        .WithMany("StudentSections")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Teacher", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.TeacherExperience", "TeacherExperience")
                        .WithMany()
                        .HasForeignKey("TeacherExperienceId")
                        .HasConstraintName("FK_teacher_experience_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.TeacherExperience", null)
                        .WithOne("Teacher")
                        .HasForeignKey("BitCollegeWeb.Entities.Teacher", "TeacherExperienceId1");

                    b.Navigation("TeacherExperience");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TeacherExperience", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Company", "Company")
                        .WithMany("TeacherExperiences")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TeacherSection", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.Section", "Section")
                        .WithMany("TeacherSections")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_section_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.Teacher", "Teacher")
                        .WithMany("TeacherSections")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.URL", b =>
                {
                    b.HasOne("BitCollegeWeb.Entities.ExternalTool", "ExternalTool")
                        .WithMany("URLS")
                        .HasForeignKey("ExternalToolId")
                        .HasConstraintName("FK_external_tool_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCollegeWeb.Entities.Topic", "Topic")
                        .WithMany("URLS")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("FK_topic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalTool");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.CalificationAssignment", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.CalificationExam", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.CalificationSystem", b =>
                {
                    b.Navigation("CalificationSystemTypeCalifications");

                    b.Navigation("ProgrammingStudy");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Classroom", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("ClassroomExternalTools");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Company", b =>
                {
                    b.Navigation("TeacherExperiences");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Day", b =>
                {
                    b.Navigation("ScheduleDays");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.ExternalTool", b =>
                {
                    b.Navigation("ClassroomExternalTools");

                    b.Navigation("URLS");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Institution", b =>
                {
                    b.Navigation("StudentExperiences");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.ProgrammingStudy", b =>
                {
                    b.Navigation("GeneralInformations");

                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Schedule", b =>
                {
                    b.Navigation("ScheduleDays");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Section", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Assignments");

                    b.Navigation("Classrooms");

                    b.Navigation("Exams");

                    b.Navigation("SectionTypeSections");

                    b.Navigation("StudentSections");

                    b.Navigation("TeacherSections");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Student", b =>
                {
                    b.Navigation("Inscriptions");

                    b.Navigation("Notifications");

                    b.Navigation("Registrations");

                    b.Navigation("Schedules");

                    b.Navigation("StudentSections");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.StudentExperience", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Teacher", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Notifications");

                    b.Navigation("Registrations");

                    b.Navigation("TeacherSections");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TeacherExperience", b =>
                {
                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TeacherForum", b =>
                {
                    b.Navigation("Classroom");

                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.Topic", b =>
                {
                    b.Navigation("GeneralInformations");

                    b.Navigation("URLS");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TypeCalification", b =>
                {
                    b.Navigation("CalificationSystemTypeCalifications");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TypeProgrammingClass", b =>
                {
                    b.Navigation("ProgrammingStudies");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TypeSection", b =>
                {
                    b.Navigation("SectionTypeSections");
                });

            modelBuilder.Entity("BitCollegeWeb.Entities.TypeStudy", b =>
                {
                    b.Navigation("ProgrammingStudies");
                });
#pragma warning restore 612, 618
        }
    }
}
